### ISSUE TITLE
HU18 - Modelamiento general de la base de datos

### ISSUE THREAD

**Issue by FabricaAdso** [FabricaAdso/lisa-back#13]
## Assignado a:
<table>
    <thead>
        <tr>
            <th>Ficha</th>
            <th>Programa</th>
            <th>Documento</th>
            <th>Nombres</th>
            <th>Apellidos</th>
        </tr>
      </thead>
      <tbody>
         <tr>
          <td>2774315</td>
          <td>ADSO</td>
          <td>1061701851</td>
          <td>Jhon Alexander</td>
          <td>Urbano Pardo</td>
        </tr>
        <tr>
          <td>2774315</td>
          <td>ADSO</td>
          <td>1006848309</td>
          <td>Gabriela Jineth</td>
          <td>Diaz Gomez</td>
        </tr>
        <tr>
          <td>2774315</td>
          <td>Adso</td>
          <td>1002958845</td>
          <td>Antonio Jose</td>
          <td>Rodriguez Atuesta</td>
        </tr>
        <tr>
          <td>2774315</td>
          <td>ADSO</td>
          <td>1061698429</td>
          <td>Camilo Alejandro</td>
          <td>Maca Bastidas</td>
        </tr>
      </tbody>
</table>

# Objetivo:
Crear un modelo general de la base de datos para el proyecto lisa.

**Comment by GabyD12** [comment]
[Diagrama drawio](https://app.diagrams.net/#G1smMlLT2qUGOW0M8CgHl1QHDfd-rk1f6o#%7B%22pageId%22%3A%223NpUXUoqLShf5Ft1mxnm%22%7D)

**Comment by FabricaAdso** [comment]
### Nuevas tablas:
* [ ] Agregar al modelo, las tablas de competencia y resultado de aprendizaje.
