### ISSUE TITLE
HU24 - Crear seeders de centros de formación y regionales.

### ISSUE THREAD

**Issue by FabricaAdso** [FabricaAdso/lisa-back#18]
## Assignado a:
<table>
    <thead>
        <tr>
            <th>Ficha</th>
            <th>Programa</th>
            <th>Documento</th>
            <th>Nombres</th>
            <th>APellidos</th>
        </tr>
      </thead>
      <tbody>
         <tr>
          <td>2774315</td>
          <td>ADSO</td>
          <td>1006848309</td>
          <td>Gabriela Jineth</td>
          <td>Diaz Gomez</td>
        </tr>
      </tbody>
</table>

# Objetivo:
Llenar las tablas de training centres y regional.
## Criterios:
Los datos de regional y centro de formación se llenan 1 sola vez, por esto requerimos:
* [x] Seeder de centros de formación.
* [x] Seeder de regionales.

**Comment by GabyD12** [comment]
Se Modifico las relaciones a nivel de modelo con base a la actualizacion del modelo relacional
