### ISSUE TITLE
HU26  - Ajustes a fichas.

### ISSUE THREAD

**Issue by FabricaAdso** [FabricaAdso/lisa-back#20]
## Assignado a:
<table>
    <thead>
        <tr>
            <th>Ficha</th>
            <th>Programa</th>
            <th>Documento</th>
            <th>Nombres</th>
            <th>APellidos</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
</table>

# Objetivo:
Ajustar la ficha para que cumpla los requerimientos.
* [x] Revisar el correcto funcionamiento del crud despues de los cambios hechos en las migraciones.
### Lider, vocero, suplente:
* [x] Crear la relación entre instructor y ficha, para asignar un lider.
* [x] Crear la relación entre aprendiz y ficha para asignar vocero y vice vocero.
* [x] Crear polices para que solo el lider pueda modificar vocero y suplente.
* [x] Crear un police que solo el coordinador del centro pueda actualizar el lider de la ficha.
* [x] Añadir el campo estado(terminada por fecha, en ejecución, terminada, terminada por unificación).
* [x] Añadir el campo etapa(PRACTICA, LECTIVA).
### Endpoinst:
* [x] Crear un endpoint que traiga las fichas en las que el instructor tiene sesiones pendientes.
* [x]  Crear un endpoint que traiga las fichas donde el instructor tuvo formación.

**Comment by CamiloMaca** [comment]
* [x] Al momento de registrar una falta crear una justificación
* [x] Crear endpoint para ver si al momento de ingresar la justificación no han pasado 3 días hábiles desde la falta, en caso de no pasar 3 días hábiles no debe poder subir justificación.
* [ ] Aprobation
* [x] Crear un endpoint para cada caso.
* [x] En caso de pasar los 3 días hábiles y no haber cargado justificación o no estar aprobada debe pasar a estado Vencidas
* [ ] En caso de aprobar la justificación debe pasar a estado Aprobada
* [ ] En caso de rechazar la justificación agregar un motivo luego esta debe pasar a estado Rechazado
* [x] En caso de estar en tiempo y no haber cargado justificación pasar a estado Pendiente 
* [ ] En caso de Rechazar y estar en tiempo poder volver a subir la justificación y pasar a Pendiente

**Comment by FabricaAdso** [comment]
# Ajustes:
* [x] Las sesiones deben cargar a partir del usuario que inicio sesión.
